### ISSUE TITLE
Error in running lammps example

### ISSUE THREAD

**Issue by tengzhang48** [nufeb/NUFEB-dev#5]
Hello,

I installed Nufeb package and can run the examples provided in the folder "NUFEB-dev/examples". But I got "Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))" error when running examples in the lammps folder "NUFEB-dev/lammps/examples".

I tried granular examples and lj melt examples and got the same errors. I understand that the information is very vague. Is there any setup I should pay attention when installing NUFEB?

Also, when I tried to install "USER-PLASMID" package, the dump.cpp file cannot successfully connect "fix_property_plasmid.h" file. Could you please take a look at this as well? 

Thanks.

Best,
Teng

**Comment by shelllbw** [comment]
Hi Teng, it seems to be a compatibility issue. We've yet to check if all lammps default examples are compatible with NUFEB. I will take a look both issues and get back to you soon.

Bowen

**Comment by tengzhang48** [comment]
Hi Bowen,

Sounds very good. Yes, I think so. On the cluster, I already installed LAMMPS of different versions and they work well. 

Thanks for your quick reply. 

Best,
Teng

**Comment by shelllbw** [comment]
Done. It should work now.

**Comment by tengzhang48** [comment]
Yes, both issues are resolved. Thanks a lot.

Just a note that, when I used git clone to download nufeb-dev from github, it does not automatically download lammps. This is not big problem as I can download the specified lammps version manually. I am not sure whether this is some set up of git command or some setup on your side.

**Comment by shelllbw** [comment]
lammps is treated as a submodule in the nufeb repo. You can use --recursive to fetch it (and libraries in /thirdparty)
git clone https://github.com/nufeb/NUFEB-dev --recursive

**Comment by tengzhang48** [comment]
Sounds very good. I do not have further questions for now. Nufeb provides very interesting functions, and I will try some simulations first. 

Thanks a lot.

Best,
Teng
